LICENSE.md

Add CC0 license

---

.travis.yml
Gemfile
Gemfile.lock

Updates Ruby to 2.2.3
Additional updates I needed to run:
nio4r to 1.2.0
libv8 to 3.16.14.13

Updates gems for compatibility with OS X 10.11

---

app/controllers/messages_controller.rb
app/views/messages/show.slim
spec/features/user_messaging_feature_spec.rb

Addresses issue #23 
Also adds feature specs

Hides expiration warning when message already deleted

---

app/models/message.rb
app/views/messages/_form.slim
config/application.rb
spec/models/message_spec.rb

Also adds specs and error messaging

Adds validation to prevent zero max_views

---

README.md

Adds semver badge

---

Gemfile
app/controllers/messages_controller.rb
app/views/layouts/application.slim
app/views/messages/gone.slim
app/views/messages/new.slim
app/views/messages/show.slim
config/locales/en.yml
spec/features/translations_feature_spec.rb
spec/features/user_messaging_feature_spec.rb
spec/missing_translations_helper.rb
spec/rails_helper.rb

Addresses issue #12 
Adds I18n support for views and flash messaging. 
Also adds specs for views and general translation error check.

Internationalizes strings 

---

README.md

Looks like gemnasium is already configured 🚀

Show gemnasium badge.

---

app/views/layouts/application.slim

Point links to current git url.

---

app/assets/stylesheets/fugacious.css.scss

CSS: Preserve line breaks in messages

---

Gemfile
Gemfile.lock
bin/cf-start
config/puma.rb
manifest-app.yml

As recommended by
https://docs.cloudfoundry.org/buildpacks/prod-server.html.

Serve app with puma.

---

CONTRIBUTING.md
README.md

Adds bin/setup for quick app setup
Adds Procfile for use with foreman
Updates README's getting started and contributing
Adds CONTRIBUTING.md

Updates setup and adds CONTRIBUTING.md

---

.gitignore
config/sidekiq_schedule.yml

Forgot to check this in earlier, mostly because I was being absentminded but also partly because we're configuring git to ignore all yaml files in the config directory. I'm also updating that rule in .gitignore because there are already a bunch of yaml files checked in, and because it looks like we're keeping secrets in the environment and not in files. If that's not the case, let me know, and I'll revert that change.

Check in cron config and update .gitignore.

---

README.md
app.json
bin/heroku
config/secrets.yml

#88 included the Procfile which adds background worker role to Heroku
Adds script to setup and launch Heroku instance
Updates secrets.yml
Updates README with instructions

Configures app for Heroku

---

db/schema.rb

Syncs db schema.rb

---

Dockerfile
README.md
bin/setup
docker-compose.yml

Allows developers to start a development instance quickly!
This is a first-pass and can be optimized

Adds basic docker dev setup

---

app/helpers/application_helper.rb
app/helpers/messages_helper.rb
app/views/layouts/application.slim
app/views/messages/_form.slim
app/views/messages/new.slim
app/views/messages/show.slim
config/locales/en.yml

Initial changes to the application.

Initial modifications to ruby code

---

app/assets/stylesheets/components/fugacious.scss
app/assets/stylesheets/components/uswds_overrides.scss

- Updated text area for secret message to be 100% width
- Updated lead font size and family per designs
- Added background positioning for error messaging

Small style tweaks

---

config/locales/en.yml

- Removing unused items
- Updating GitHub casing

Updating copy

---

app/views/layouts/application.slim
app/views/messages/_form.slim
app/views/messages/new.slim
app/views/messages/show.slim
app/views/pages/about.html.slim
app/views/pages/privacy.html.slim
config/locales/en.yml

- Updating class code to modernize
- Adding disabled property to secret message textarea so you can’t
accidentally delete the message!
- Adding locale tags for content that was not in the en file
- Minor HTML tweaks to strong tag items

Minor tweaks to code and updates to use new en variables

---

app/views/pages/privacy.html.slim
config/locales/en.yml

En file updated and the privacy page also updated

Adding content for privacy policy page

---

spec/controllers/messages_controller_spec.rb

* Just for clarity / ease of reading. No functional changes except moving away from instance var, which means we needed a different expectation for one spec.

Refactor message controller spec

---

app/assets/stylesheets/components/uswds_overrides.scss
app/views/messages/show.slim

Make the delete button look like a link

Updates to delete button styling

---

Gemfile.lock

Resolves https://github.com/fugacious/fugacious/issues/125

Upgrades nokogiri gem to 1.7.1

---

README.md

Include note for operators about sensitive information re https://github.com/fugacious/fugacious/issues/123

Update README for operator note

---

README.md
app.json
config/application.rb
config/secrets.yml

Adds app_name to heroku deploy script
Alpha sorts keys secrets.yml and app.json
Updates README

Improves app name configuration and documentation

---

Gemfile
Gemfile.lock

Addresses latest Hakiri violations

Updates dependencies

---

Gemfile
config/database.yml

specified pg version and modified database.yml

modify production settings
